databases:
  - name: aks-postgres
    databaseName: project_aks
    user: aks_admin
    plan: free

services:
  # 1. Spring Boot AKS Core Service
  - type: web
    name: coreservices-aks
    env: docker
    rootDir: Backend/coreservices_AKS
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: spring.datasource.url
        fromDatabase:
          name: aks-postgres
          property: connectionString
      - key: spring.datasource.username
        fromDatabase:
          name: aks-postgres
          property: user
      - key: spring.datasource.password
        fromDatabase:
          name: aks-postgres
          property: password

  # 2. Spring Boot Mongo Auth Service
  - type: web
    name: coreservices-mongo
    env: docker
    rootDir: Backend/coreservices_mongo
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: spring.data.mongodb.uri
        value: mongodb+srv://admin:admin123@cluster0.q9ybvvg.mongodb.net/STEM?retryWrites=true&w=majority&appName=Cluster0

  # 3. Node.js Review Service
  - type: web
    name: node-service
    env: docker
    rootDir: Backend/node_service
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin:admin123@cluster0.q9ybvvg.mongodb.net/STEM?retryWrites=true&w=majority&appName=Cluster0

  # 4. FastAPI Gateway
  - type: web
    name: aks-gateway
    env: docker
    rootDir: Backend/gateway
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_URL
        fromService:
          type: web
          name: coreservices-aks
          property: host
      - key: MONGO_SPRING_URL
        fromService:
          type: web
          name: coreservices-mongo
          property: host
      - key: NODE_SERVICE_URL
        fromService:
          type: web
          name: node-service
          property: host

  # 5. Frontend React App
  - type: web
    name: aks-frontend
    env: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: aks-gateway
          property: host
