spring.application.name=coreservices

#Server Port
server.port=${PORT:8020}

#MongoDB Configuration
spring.mongodb.uri=mongodb+srv://test:admin@cluster0.hxyc73f.mongodb.net/Accessible_Knowledge_System?appName=Cluster0
spring.mongodb.database=Accessible_Knowledge_System

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
